version: "3.7"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - accommodation-service
      - reservation-service
    ports:
      - "4000:4000"
  user-service:
    image: aleksandarb99/user:latest
    environment:
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: user-db
      DATABASE_SCHEMA: user
      DATABASE_PORT: 5432
      AUTH_URL: http://user-service:8080
      RESERVATION_URL: http://reservation-service:8080/api/v1/reservation
      ACCOMMODATION_URL: http://accommodation-service:8080/api/v1/accommodation
    depends_on:
      user-db:
        condition: service_healthy
  accommodation-service:
    image: aleksandarb99/accommodation:latest
    environment:
      DATABASE_USERNAME: accommodation
      DATABASE_PASSWORD: admin
      DATABASE_DOMAIN: accommodation-db
      DATABASE_SCHEMA: accommodation
      DATABASE_PORT: 5432
      AUTH_URL: http://user-service:8080
      RESERVATION_URL: http://reservation-service:8080/api/v1/reservation
    depends_on:
      accommodation-db:
        condition: service_healthy
      user-service:
  user-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 6
    container_name: user-db
    volumes:
      - postgres_user:/var/lib/postgresql/data
  accommodation-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=accommodation
      - POSTGRES_USER=accommodation
      - POSTGRES_PASSWORD=admin
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U accommodation" ]
      interval: 10s
      timeout: 5s
      retries: 6
    container_name: accommodation-db
    volumes:
      - postgres_accommodation:/var/lib/postgresql/data
  reservation-service:
    image: aleksandarb99/reservation:latest
    environment:
      DATABASE_DOMAIN: reservation-db
      DATABASE_SCHEMA: reservation
      DATABASE_PORT: 27017
      AUTH_URL: http://user-service:8080
      ACCOMMODATION_URL: http://accommodation-service:8080/api/v1/accommodation
      USER_URL: http://user-service:8080/api/v1/user
    depends_on:
      - reservation-db
      - user-service
  reservation-db:
    container_name: reservation-db
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: reservation
    volumes:
      - postgres_reservation:/data/db
volumes:
  postgres_user:
  postgres_accommodation:
  postgres_reservation: